### ISSUE TITLE
Integers

### ISSUE THREAD

**Issue by web-dev-sam** [Saboti215/SB2JS#2]
x = 256   '
x = 0x100 ' Hexadecimal form 1
x = &h100 ' Hexadecimal form 2
x = 0o400 ' Octal form 1
x = &o400 ' Octal form 2
x = 0b111 ' Binary form 1
x = &b111 ' Binary form 2

**Comment by Saboti215** [comment]
Same notation as in JavaScript, so I do not have to convert these.

**Comment by Saboti215** [comment]
Same notation in JS, so I do not have to convert them. 
Only think of it in a for-loop
